# https://blog.csdn.net/magi1201/article/details/112872808
# https://github.com/alibaba/spring-cloud-alibaba/blob/master/pom.xml
server:
  port: 7079

spring:
  application:
    name: nacos-client
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
